version: '3.7'
services:
  fb_handler:
    image: allyotov/behemoth_fb_group_handler:1.0.0
    networks:
      - behemoth
    env_file: .env

  backend:
    image: allyotov/behemoth_backend:1.0.3
    networks:
      - behemoth
    env_file: .env
    ports:
      - 8000:8000
    volumes:
      - ./backend_data:/behemoth_backend/behemoth_data

  bot:
    image: allyotov/behemoth_bot:1.0.0
    networks:
      - behemoth
    env_file: .env

networks:
  behemoth: